export interface Painting {
  id: string
  title: string
  titleZh: string
  artist: string
  artistZh: string
  year: string
  imageUrl: string
  dominantColors: string[]
  style: string
  description: string
}

export const FAMOUS_PAINTINGS: Painting[] = [
  // ─── 梵高 ────────────────────────────────────────────────
  {
    id: 'starry-night',
    title: 'The Starry Night',
    titleZh: '星空',
    artist: 'Vincent van Gogh',
    artistZh: '文森特·梵高',
    year: '1889',
    imageUrl: '/paintings/starry-night.jpg',
    dominantColors: ['#1A237E', '#283593', '#4A90D9', '#F5D042', '#2E3B4E'],
    style: '后印象派',
    description: '梵高最著名的作品之一，以漩涡状笔触表现夜空的动感与神秘。',
  },
  {
    id: 'sunflowers',
    title: 'Sunflowers',
    titleZh: '向日葵',
    artist: 'Vincent van Gogh',
    artistZh: '文森特·梵高',
    year: '1888',
    imageUrl: '/paintings/sunflowers.jpg',
    dominantColors: ['#FFD700', '#FFA500', '#DAA520', '#8B7355', '#CD8500'],
    style: '后印象派',
    description: '以鲜艳黄色系展现向日葵的生命力，是梵高最具代表性的静物画系列。',
  },
  {
    id: 'bedroom',
    title: 'The Bedroom',
    titleZh: '卧室',
    artist: 'Vincent van Gogh',
    artistZh: '文森特·梵高',
    year: '1888',
    imageUrl: '/paintings/bedroom.jpg',
    dominantColors: ['#5B8DB8', '#8B6914', '#E8C870', '#C8A060', '#7A9DB0'],
    style: '后印象派',
    description: '梵高在阿尔勒的卧室，以明亮色彩传递宁静与安慰之感。',
  },
  {
    id: 'cafe-terrace',
    title: 'Café Terrace at Night',
    titleZh: '夜晚的咖啡馆露台',
    artist: 'Vincent van Gogh',
    artistZh: '文森特·梵高',
    year: '1888',
    imageUrl: '/paintings/cafe-terrace.jpg',
    dominantColors: ['#F5D070', '#3A3A6A', '#2A4A2A', '#8B7050', '#C8A840'],
    style: '后印象派',
    description: '用互补色表现灯光与星空，是梵高首幅以星夜为主题的油画。',
  },

  // ─── 莫奈 ────────────────────────────────────────────────
  {
    id: 'water-lilies',
    title: 'Water Lilies',
    titleZh: '睡莲',
    artist: 'Claude Monet',
    artistZh: '克劳德·莫奈',
    year: '1906',
    imageUrl: '/paintings/water-lilies.jpg',
    dominantColors: ['#2E7D32', '#558B2F', '#7CB9D8', '#A5D6A7', '#1B5E20'],
    style: '印象派',
    description: '莫奈晚年巨作，描绘吉维尼花园水面上的睡莲，光影变幻迷人。',
  },
  {
    id: 'impression-sunrise',
    title: 'Impression, Sunrise',
    titleZh: '印象·日出',
    artist: 'Claude Monet',
    artistZh: '克劳德·莫奈',
    year: '1872',
    imageUrl: '/paintings/impression-sunrise.jpg',
    dominantColors: ['#2C3E50', '#1A237E', '#FF6B35', '#F39C12', '#4A6741'],
    style: '印象派',
    description: '印象派运动命名之作，朦胧笔触描绘勒阿弗尔港口晨曦。',
  },
  {
    id: 'woman-parasol',
    title: 'Woman with a Parasol',
    titleZh: '撑阳伞的女人',
    artist: 'Claude Monet',
    artistZh: '克劳德·莫奈',
    year: '1875',
    imageUrl: '/paintings/woman-parasol.jpg',
    dominantColors: ['#87CEEB', '#F5F5DC', '#2E7D32', '#D4AF8C', '#6B8E23'],
    style: '印象派',
    description: '逆光构图，以流动笔触捕捉阳光与微风，是印象派户外绘画的典范。',
  },
  {
    id: 'haystacks',
    title: 'Haystacks',
    titleZh: '干草垛',
    artist: 'Claude Monet',
    artistZh: '克劳德·莫奈',
    year: '1890',
    imageUrl: '/paintings/haystacks.jpg',
    dominantColors: ['#C8A060', '#8BA88B', '#D4B896', '#7A9090', '#E8C870'],
    style: '印象派',
    description: '莫奈对同一主题在不同光线下的系列研究，探索自然光的瞬间变化。',
  },

  // ─── 达芬奇 / 文艺复兴 ──────────────────────────────────
  {
    id: 'mona-lisa',
    title: 'Mona Lisa',
    titleZh: '蒙娜丽莎',
    artist: 'Leonardo da Vinci',
    artistZh: '列奥纳多·达芬奇',
    year: '1503–1519',
    imageUrl: '/paintings/mona-lisa.jpg',
    dominantColors: ['#8B7355', '#A0845C', '#6B5B45', '#D4B896', '#4A3728'],
    style: '文艺复兴',
    description: '世界最著名的肖像画，以神秘微笑和精湛的晕涂法技艺著称。',
  },
  {
    id: 'birth-of-venus',
    title: 'The Birth of Venus',
    titleZh: '维纳斯的诞生',
    artist: 'Sandro Botticelli',
    artistZh: '桑德罗·波提切利',
    year: '1484–1486',
    imageUrl: '/paintings/birth-of-venus.jpg',
    dominantColors: ['#87CEEB', '#F5DEB3', '#8B7355', '#E8C49A', '#4682B4'],
    style: '文艺复兴',
    description: '爱与美之女神从海中诞生，是文艺复兴时期神话题材绘画的代表作。',
  },
  {
    id: 'school-of-athens',
    title: 'The School of Athens',
    titleZh: '雅典学院',
    artist: 'Raphael',
    artistZh: '拉斐尔',
    year: '1509–1511',
    imageUrl: '/paintings/school-of-athens.jpg',
    dominantColors: ['#C8A870', '#8B7355', '#A0845C', '#D4B896', '#6B5B45'],
    style: '文艺复兴',
    description: '拉斐尔在梵蒂冈宫的壁画，描绘古希腊哲人云集一堂，是文艺复兴巅峰之作。',
  },

  // ─── 巴洛克 ──────────────────────────────────────────────
  {
    id: 'girl-with-pearl',
    title: 'Girl with a Pearl Earring',
    titleZh: '戴珍珠耳环的少女',
    artist: 'Johannes Vermeer',
    artistZh: '约翰内斯·维米尔',
    year: '1665',
    imageUrl: '/paintings/girl-with-pearl.jpg',
    dominantColors: ['#2C2416', '#8B7355', '#F5DEB3', '#4A3728', '#D4AF8C'],
    style: '巴洛克',
    description: '荷兰最著名的肖像画，以深暗背景衬托少女的神秘眼神与珍珠耳环。',
  },
  {
    id: 'night-watch',
    title: 'The Night Watch',
    titleZh: '夜巡',
    artist: 'Rembrandt van Rijn',
    artistZh: '伦勃朗·范·莱因',
    year: '1642',
    imageUrl: '/paintings/night-watch.jpg',
    dominantColors: ['#2C2416', '#8B7355', '#DAA520', '#4A3728', '#F5DEB3'],
    style: '巴洛克',
    description: '伦勃朗最重要的作品，以戏剧性光影对比展现民兵队伍的活力与张力。',
  },
  {
    id: 'las-meninas',
    title: 'Las Meninas',
    titleZh: '宫娥',
    artist: 'Diego Velázquez',
    artistZh: '迭戈·委拉斯凯兹',
    year: '1656',
    imageUrl: '/paintings/las-meninas.jpg',
    dominantColors: ['#4A3728', '#2C2416', '#8B7355', '#D4B896', '#6B5B45'],
    style: '巴洛克',
    description: '西班牙巴洛克巅峰之作，以复杂的空间构图打破绘画与现实的边界。',
  },

  // ─── 印象派 ──────────────────────────────────────────────
  {
    id: 'moulin-galette',
    title: 'Dance at Le Moulin de la Galette',
    titleZh: '煎饼磨坊的舞会',
    artist: 'Pierre-Auguste Renoir',
    artistZh: '皮埃尔·奥古斯特·雷诺阿',
    year: '1876',
    imageUrl: '/paintings/moulin-galette.jpg',
    dominantColors: ['#3A4A6A', '#8B7355', '#C8A060', '#5A6A9A', '#D4B896'],
    style: '印象派',
    description: '雷诺阿最重要的代表作，光斑点缀的户外舞会洋溢着欢快的生命气息。',
  },
  {
    id: 'blue-dancers',
    title: 'Blue Dancers',
    titleZh: '蓝色舞者',
    artist: 'Edgar Degas',
    artistZh: '埃德加·德加',
    year: '1897',
    imageUrl: '/paintings/blue-dancers.jpg',
    dominantColors: ['#4A7AB8', '#8AB4D8', '#C8D8E8', '#F0D8A0', '#6890C0'],
    style: '印象派',
    description: '德加舞蹈系列的代表作，蓝色调营造出轻盈飘逸的舞台氛围。',
  },
  {
    id: 'boating-party',
    title: 'Luncheon of the Boating Party',
    titleZh: '船上的午宴',
    artist: 'Pierre-Auguste Renoir',
    artistZh: '皮埃尔·奥古斯特·雷诺阿',
    year: '1881',
    imageUrl: '/paintings/boating-party.jpg',
    dominantColors: ['#3A5A3A', '#C8A060', '#D4B896', '#8B4513', '#6A8A6A'],
    style: '印象派',
    description: '雷诺阿以丰富色彩记录朋友们在塞纳河畔船上欢聚的轻松午后。',
  },

  // ─── 后印象派 ────────────────────────────────────────────
  {
    id: 'card-players',
    title: 'The Card Players',
    titleZh: '玩纸牌者',
    artist: 'Paul Cézanne',
    artistZh: '保罗·塞尚',
    year: '1892–1895',
    imageUrl: '/paintings/card-players.jpg',
    dominantColors: ['#8B6914', '#6B4A28', '#C8A060', '#4A3A28', '#A08050'],
    style: '后印象派',
    description: '塞尚以几何化的形体构建画面，开创了现代绘画的先河。',
  },
  {
    id: 'where-do-we-come',
    title: 'Where Do We Come From? What Are We? Where Are We Going?',
    titleZh: '我们从哪里来？我们是什么？我们往哪里去？',
    artist: 'Paul Gauguin',
    artistZh: '保罗·高更',
    year: '1897–1898',
    imageUrl: '/paintings/where-do-we-come.jpg',
    dominantColors: ['#2E5A2E', '#8B6914', '#C8A060', '#4A7A4A', '#D4B896'],
    style: '后印象派',
    description: '高更最重要的哲学性巨作，在塔希提岛创作，探讨生命的意义。',
  },
  {
    id: 'vision-sermon',
    title: 'Vision After the Sermon',
    titleZh: '布道后的幻象',
    artist: 'Paul Gauguin',
    artistZh: '保罗·高更',
    year: '1888',
    imageUrl: '/paintings/vision-sermon.jpg',
    dominantColors: ['#C83228', '#2A3A2A', '#F5DEB3', '#8B1A1A', '#D4A090'],
    style: '后印象派',
    description: '大面积鲜红背景极具冲击力，标志着高更走向象征主义的转变。',
  },

  // ─── 表现主义 ─────────────────────────────────────────────
  {
    id: 'the-scream',
    title: 'The Scream',
    titleZh: '呐喊',
    artist: 'Edvard Munch',
    artistZh: '爱德华·蒙克',
    year: '1893',
    imageUrl: '/paintings/the-scream.jpg',
    dominantColors: ['#C0392B', '#E67E22', '#F39C12', '#2C3E50', '#8B4513'],
    style: '表现主义',
    description: '以扭曲线条和强烈色彩表达内心的恐惧与焦虑，是心理表现主义的标志。',
  },

  // ─── 新艺术运动 ───────────────────────────────────────────
  {
    id: 'the-kiss-klimt',
    title: 'The Kiss',
    titleZh: '吻',
    artist: 'Gustav Klimt',
    artistZh: '古斯塔夫·克里姆特',
    year: '1907–1908',
    imageUrl: '/paintings/the-kiss-klimt.jpg',
    dominantColors: ['#DAA520', '#8B6914', '#F5DEB3', '#2C2416', '#C8A030'],
    style: '新艺术运动',
    description: '克里姆特黄金时期代表作，以大量金箔和华丽装饰图案表现爱情的永恒。',
  },

  // ─── 超现实主义 ───────────────────────────────────────────
  {
    id: 'persistence-of-memory',
    title: 'The Persistence of Memory',
    titleZh: '记忆的永恒',
    artist: 'Salvador Dalí',
    artistZh: '萨尔瓦多·达利',
    year: '1931',
    imageUrl: '/paintings/persistence-of-memory.jpg',
    dominantColors: ['#8B7355', '#D4B896', '#87CEEB', '#F5DEB3', '#4A3728'],
    style: '超现实主义',
    description: '超现实主义最具代表性的作品，以融化的钟表探讨时间的主观性。',
  },

  // ─── 古典主义 ─────────────────────────────────────────────
  {
    id: 'liberty-leading',
    title: 'Liberty Leading the People',
    titleZh: '自由引导人民',
    artist: 'Eugène Delacroix',
    artistZh: '欧仁·德拉克罗瓦',
    year: '1830',
    imageUrl: '/paintings/liberty-leading.jpg',
    dominantColors: ['#1A237E', '#8B1A1A', '#F5DEB3', '#2C3A2C', '#C83228'],
    style: '浪漫主义',
    description: '以三色旗为象征，表现1830年法国七月革命中人民的英勇，充满热情与动感。',
  },
  {
    id: 'raft-medusa',
    title: 'The Raft of the Medusa',
    titleZh: '梅杜萨之筏',
    artist: 'Théodore Géricault',
    artistZh: '泰奥多尔·席里柯',
    year: '1818–1819',
    imageUrl: '/paintings/raft-medusa.jpg',
    dominantColors: ['#8B6914', '#2C2416', '#C8A060', '#4A3A28', '#D4B896'],
    style: '浪漫主义',
    description: '根据真实海难事件创作，以金字塔式构图展现绝望与希望的戏剧张力。',
  },
  {
    id: 'third-of-may',
    title: 'The Third of May 1808',
    titleZh: '1808年5月3日',
    artist: 'Francisco Goya',
    artistZh: '弗朗西斯科·戈雅',
    year: '1814',
    imageUrl: '/paintings/third-of-may.jpg',
    dominantColors: ['#F5D060', '#2C2416', '#C83228', '#8B7355', '#FFFFFF'],
    style: '浪漫主义',
    description: '戈雅以白衫男子为焦点，强烈控诉战争暴行，是现代战争绘画的先驱。',
  },
  {
    id: 'olympia',
    title: 'Olympia',
    titleZh: '奥林匹亚',
    artist: 'Édouard Manet',
    artistZh: '爱德华·马奈',
    year: '1863',
    imageUrl: '/paintings/olympia.jpg',
    dominantColors: ['#F5DEB3', '#2C2416', '#4A3728', '#8B7355', '#FFFFF0'],
    style: '现代主义先驱',
    description: '马奈以直白现代手法重诠古典题材，挑战学院派规范，引发巨大争议。',
  },

  // ─── 新印象派 / 点彩 ──────────────────────────────────────
  {
    id: 'sunday-grande-jatte',
    title: 'A Sunday on La Grande Jatte',
    titleZh: '大碗岛的星期天下午',
    artist: 'Georges Seurat',
    artistZh: '乔治·修拉',
    year: '1884–1886',
    imageUrl: '/paintings/sunday-grande-jatte.jpg',
    dominantColors: ['#3A6A3A', '#8BAA6A', '#C8C890', '#4A7A4A', '#A0C090'],
    style: '点彩派',
    description: '以细小纯色圆点构成画面，是点彩派（分色主义）技法的集大成之作。',
  },

  // ─── 现代主义 ─────────────────────────────────────────────
  {
    id: 'nighthawks',
    title: 'Nighthawks',
    titleZh: '夜鹰',
    artist: 'Edward Hopper',
    artistZh: '爱德华·霍珀',
    year: '1942',
    imageUrl: '/paintings/nighthawks.jpg',
    dominantColors: ['#2A6A3A', '#C8A040', '#F5E890', '#1A2A1A', '#8BAA60'],
    style: '写实主义',
    description: '以孤寂的深夜餐厅描绘现代都市的疏离感，是美国20世纪最著名的绘画之一。',
  },
  {
    id: 'american-gothic',
    title: 'American Gothic',
    titleZh: '美国哥特式',
    artist: 'Grant Wood',
    artistZh: '格兰特·伍德',
    year: '1930',
    imageUrl: '/paintings/american-gothic.jpg',
    dominantColors: ['#8B6914', '#6B4A28', '#C8A060', '#4A3A28', '#D4B896'],
    style: '地域主义',
    description: '以农民夫妇和哥特式窗户为核心，成为美国中西部精神与价值观的象征。',
  },
]

export const PAINTERS = [...new Set(FAMOUS_PAINTINGS.map(p => p.artistZh))]
export const STYLES = [...new Set(FAMOUS_PAINTINGS.map(p => p.style))]
