export interface Painting {
  id: string;
  title: string;
  titleZh: string;
  artist: string;
  artistZh: string;
  year: string;
  imageUrl: string;
  dominantColors: string[];
  style: string;
  description: string;
  subject?: string;
  studyTags?: string[];
  studyPrompt?: string;
  museum?: string;
  sourceUrl?: string;
  license?: string;
  licenseUrl?: string;
  medium?: string;
}

export const FAMOUS_PAINTINGS: Painting[] = [
  // ─── 梵高 ────────────────────────────────────────────────
  {
    id: "starry-night",
    subject: "风景",
    studyTags: ["冷暖关系", "构图节奏"],
    studyPrompt:
      "先找蓝色和黄色各三块，比较明度；只用五条弧线概括天空的流动方向。",
    title: "The Starry Night",
    titleZh: "星空",
    artist: "Vincent van Gogh",
    artistZh: "文森特·梵高",
    year: "1889",
    imageUrl: "/paintings/starry-night.jpg",
    dominantColors: ["#1A237E", "#283593", "#4A90D9", "#F5D042", "#2E3B4E"],
    style: "后印象派",
    description: "梵高最著名的作品之一，以漩涡状笔触表现夜空的动感与神秘。",
  },
  {
    id: "sunflowers",
    subject: "静物",
    studyTags: ["色彩调和", "明暗归纳"],
    studyPrompt:
      "在黄色里区分偏橙、偏绿和偏灰的三种变化；切黑白后，检查花与花瓶是否仍有层次。",
    title: "Sunflowers",
    titleZh: "向日葵",
    artist: "Vincent van Gogh",
    artistZh: "文森特·梵高",
    year: "1888",
    imageUrl: "/paintings/sunflowers.jpg",
    dominantColors: ["#FFD700", "#FFA500", "#DAA520", "#8B7355", "#CD8500"],
    style: "后印象派",
    description:
      "以鲜艳黄色系展现向日葵的生命力，是梵高最具代表性的静物画系列。",
  },
  {
    id: "bedroom",
    subject: "室内",
    studyTags: ["空间透视", "冷暖关系"],
    studyPrompt:
      "画出床和椅子的大形，比较它们的边线方向；注意画中空间可有表现性变形，不把它当作严格透视模板。",
    title: "The Bedroom",
    titleZh: "卧室",
    artist: "Vincent van Gogh",
    artistZh: "文森特·梵高",
    year: "1888",
    imageUrl: "/paintings/bedroom.jpg",
    dominantColors: ["#5B8DB8", "#8B6914", "#E8C870", "#C8A060", "#7A9DB0"],
    style: "后印象派",
    description: "梵高在阿尔勒的卧室，以明亮色彩传递宁静与安慰之感。",
  },
  {
    id: "cafe-terrace",
    subject: "风景",
    studyTags: ["冷暖关系", "空间透视"],
    studyPrompt:
      "取灯光暖黄与天空冷蓝各一块，先比明度再比饱和度；用两条线概括街道纵深。",
    title: "Café Terrace at Night",
    titleZh: "夜晚的咖啡馆露台",
    artist: "Vincent van Gogh",
    artistZh: "文森特·梵高",
    year: "1888",
    imageUrl: "/paintings/cafe-terrace.jpg",
    dominantColors: ["#F5D070", "#3A3A6A", "#2A4A2A", "#8B7050", "#C8A840"],
    style: "后印象派",
    description: "用互补色表现灯光与星空，是梵高首幅以星夜为主题的油画。",
  },

  // ─── 莫奈 ────────────────────────────────────────────────
  {
    id: "water-lilies",
    subject: "风景",
    studyTags: ["色彩调和", "边缘虚实"],
    studyPrompt:
      "只选水面上的三种相近色，画成相邻色块；比较哪些边缘清楚、哪些融在一起。",
    title: "Water Lilies",
    titleZh: "睡莲",
    artist: "Claude Monet",
    artistZh: "克劳德·莫奈",
    year: "1906",
    imageUrl: "/paintings/water-lilies.jpg",
    dominantColors: ["#2E7D32", "#558B2F", "#7CB9D8", "#A5D6A7", "#1B5E20"],
    style: "印象派",
    description: "莫奈晚年巨作，描绘吉维尼花园水面上的睡莲，光影变幻迷人。",
  },
  {
    id: "impression-sunrise",
    subject: "风景",
    studyTags: ["冷暖关系", "构图节奏"],
    studyPrompt:
      "先画大面积灰蓝，再放一小点橙红；试着放大橙红色块，感受面积比例怎样改变焦点。",
    title: "Impression, Sunrise",
    titleZh: "印象·日出",
    artist: "Claude Monet",
    artistZh: "克劳德·莫奈",
    year: "1872",
    imageUrl: "/paintings/impression-sunrise.jpg",
    dominantColors: ["#2C3E50", "#1A237E", "#FF6B35", "#F39C12", "#4A6741"],
    style: "印象派",
    description: "印象派运动命名之作，朦胧笔触描绘勒阿弗尔港口晨曦。",
  },
  {
    id: "woman-parasol",
    subject: "人物",
    studyTags: ["明暗归纳", "冷暖关系"],
    studyPrompt:
      "切黑白比较人物与天空的明度，回到彩色观察白裙中的冷暖色；白色物体不等于只用白颜料。",
    title: "Woman with a Parasol",
    titleZh: "撑阳伞的女人",
    artist: "Claude Monet",
    artistZh: "克劳德·莫奈",
    year: "1875",
    imageUrl: "/paintings/woman-parasol.jpg",
    dominantColors: ["#87CEEB", "#F5F5DC", "#2E7D32", "#D4AF8C", "#6B8E23"],
    style: "印象派",
    description: "逆光构图，以流动笔触捕捉阳光与微风，是印象派户外绘画的典范。",
  },
  {
    id: "haystacks",
    subject: "风景",
    studyTags: ["冷暖关系", "明暗归纳"],
    studyPrompt:
      "把草垛概括成一个体积，分别取受光面与背光面的色；先比较亮暗，再比较冷暖。",
    title: "Haystacks",
    titleZh: "干草垛",
    artist: "Claude Monet",
    artistZh: "克劳德·莫奈",
    year: "1890",
    imageUrl: "/paintings/haystacks.jpg",
    dominantColors: ["#C8A060", "#8BA88B", "#D4B896", "#7A9090", "#E8C870"],
    style: "印象派",
    description: "莫奈对同一主题在不同光线下的系列研究，探索自然光的瞬间变化。",
  },

  // ─── 达芬奇 / 文艺复兴 ──────────────────────────────────
  {
    id: "mona-lisa",
    subject: "人物",
    studyTags: ["边缘虚实", "明暗归纳"],
    studyPrompt:
      "观察脸部亮面怎样缓缓转入暗面；练一条从浅到深的柔和灰阶，避免在鼻翼周围画硬轮廓。",
    title: "Mona Lisa",
    titleZh: "蒙娜丽莎",
    artist: "Leonardo da Vinci",
    artistZh: "列奥纳多·达芬奇",
    year: "1503–1519",
    imageUrl: "/paintings/mona-lisa.jpg",
    dominantColors: ["#8B7355", "#A0845C", "#6B5B45", "#D4B896", "#4A3728"],
    style: "文艺复兴",
    description: "世界最著名的肖像画，以神秘微笑和精湛的晕涂法技艺著称。",
  },
  {
    id: "birth-of-venus",
    subject: "叙事",
    studyTags: ["构图节奏", "边缘虚实"],
    studyPrompt:
      "先用简单线条概括人物姿态与头发方向；观察轮廓线怎样把人物从背景中分离出来。",
    title: "The Birth of Venus",
    titleZh: "维纳斯的诞生",
    artist: "Sandro Botticelli",
    artistZh: "桑德罗·波提切利",
    year: "1484–1486",
    imageUrl: "/paintings/birth-of-venus.jpg",
    dominantColors: ["#87CEEB", "#F5DEB3", "#8B7355", "#E8C49A", "#4682B4"],
    style: "文艺复兴",
    description: "爱与美之女神从海中诞生，是文艺复兴时期神话题材绘画的代表作。",
  },
  {
    id: "school-of-athens",
    subject: "室内",
    studyTags: ["空间透视", "构图节奏"],
    studyPrompt:
      "找出建筑通向远处的边线并延长，观察汇聚区域；再把人群分成几个大小不同的形。",
    title: "The School of Athens",
    titleZh: "雅典学院",
    artist: "Raphael",
    artistZh: "拉斐尔",
    year: "1509–1511",
    imageUrl: "/paintings/school-of-athens.jpg",
    dominantColors: ["#C8A870", "#8B7355", "#A0845C", "#D4B896", "#6B5B45"],
    style: "文艺复兴",
    description:
      "拉斐尔在梵蒂冈宫的壁画，描绘古希腊哲人云集一堂，是文艺复兴巅峰之作。",
  },

  // ─── 巴洛克 ──────────────────────────────────────────────
  {
    id: "girl-with-pearl",
    subject: "人物",
    studyTags: ["明暗归纳", "边缘虚实"],
    studyPrompt:
      "先画脸部的亮与暗两块，再保留一个最亮小点；检查暗侧脸缘是否可以融入背景。",
    title: "Girl with a Pearl Earring",
    titleZh: "戴珍珠耳环的少女",
    artist: "Johannes Vermeer",
    artistZh: "约翰内斯·维米尔",
    year: "1665",
    imageUrl: "/paintings/girl-with-pearl.jpg",
    dominantColors: ["#2C2416", "#8B7355", "#F5DEB3", "#4A3728", "#D4AF8C"],
    style: "巴洛克",
    description: "荷兰最著名的肖像画，以深暗背景衬托少女的神秘眼神与珍珠耳环。",
  },
  {
    id: "night-watch",
    subject: "叙事",
    studyTags: ["明暗归纳", "构图节奏"],
    studyPrompt:
      "切黑白，圈出三处最亮的区域；把其余人物合并成暗形，观察亮部怎样引导视线。",
    title: "The Night Watch",
    titleZh: "夜巡",
    artist: "Rembrandt van Rijn",
    artistZh: "伦勃朗·范·莱因",
    year: "1642",
    imageUrl: "/paintings/night-watch.jpg",
    dominantColors: ["#2C2416", "#8B7355", "#DAA520", "#4A3728", "#F5DEB3"],
    style: "巴洛克",
    description:
      "伦勃朗最重要的作品，以戏剧性光影对比展现民兵队伍的活力与张力。",
  },
  {
    id: "las-meninas",
    subject: "室内",
    studyTags: ["空间透视", "明暗归纳"],
    studyPrompt: "找出门口的亮块和前景人物的亮块，再用三条线概括房间的深度。",
    title: "Las Meninas",
    titleZh: "宫娥",
    artist: "Diego Velázquez",
    artistZh: "迭戈·委拉斯凯兹",
    year: "1656",
    imageUrl: "/paintings/las-meninas.jpg",
    dominantColors: ["#4A3728", "#2C2416", "#8B7355", "#D4B896", "#6B5B45"],
    style: "巴洛克",
    description: "西班牙巴洛克巅峰之作，以复杂的空间构图打破绘画与现实的边界。",
  },

  // ─── 印象派 ──────────────────────────────────────────────
  {
    id: "moulin-galette",
    subject: "人物",
    studyTags: ["冷暖关系", "构图节奏"],
    studyPrompt:
      "先把人群合并为大色团，再挑出三个阳光亮斑；不要一开始就逐张脸描绘。",
    title: "Dance at Le Moulin de la Galette",
    titleZh: "煎饼磨坊的舞会",
    artist: "Pierre-Auguste Renoir",
    artistZh: "皮埃尔·奥古斯特·雷诺阿",
    year: "1876",
    imageUrl: "/paintings/moulin-galette.jpg",
    dominantColors: ["#3A4A6A", "#8B7355", "#C8A060", "#5A6A9A", "#D4B896"],
    style: "印象派",
    description:
      "雷诺阿最重要的代表作，光斑点缀的户外舞会洋溢着欢快的生命气息。",
  },
  {
    id: "blue-dancers",
    subject: "人物",
    studyTags: ["色彩调和", "构图节奏"],
    studyPrompt:
      "找出三种不同的蓝，比较明度与偏紫、偏绿的变化；用弧线概括四个身体的方向。",
    title: "Blue Dancers",
    titleZh: "蓝色舞者",
    artist: "Edgar Degas",
    artistZh: "埃德加·德加",
    year: "1897",
    imageUrl: "/paintings/blue-dancers.jpg",
    dominantColors: ["#4A7AB8", "#8AB4D8", "#C8D8E8", "#F0D8A0", "#6890C0"],
    style: "印象派",
    description: "德加舞蹈系列的代表作，蓝色调营造出轻盈飘逸的舞台氛围。",
  },
  {
    id: "boating-party",
    subject: "人物",
    studyTags: ["构图节奏", "冷暖关系"],
    studyPrompt:
      "先概括遮阳篷、桌面和人群三个区域，再比较衣服冷色与肤色暖色的比例。",
    title: "Luncheon of the Boating Party",
    titleZh: "船上的午宴",
    artist: "Pierre-Auguste Renoir",
    artistZh: "皮埃尔·奥古斯特·雷诺阿",
    year: "1881",
    imageUrl: "/paintings/boating-party.jpg",
    dominantColors: ["#3A5A3A", "#C8A060", "#D4B896", "#8B4513", "#6A8A6A"],
    style: "印象派",
    description: "雷诺阿以丰富色彩记录朋友们在塞纳河畔船上欢聚的轻松午后。",
  },

  // ─── 后印象派 ────────────────────────────────────────────
  {
    id: "card-players",
    subject: "人物",
    studyTags: ["明暗归纳", "构图节奏"],
    studyPrompt:
      "把人物上身看作大块体积，比较左右两人的轮廓与桌面空隙；先画大形再加手。",
    title: "The Card Players",
    titleZh: "玩纸牌者",
    artist: "Paul Cézanne",
    artistZh: "保罗·塞尚",
    year: "1892–1895",
    imageUrl: "/paintings/card-players.jpg",
    dominantColors: ["#8B6914", "#6B4A28", "#C8A060", "#4A3A28", "#A08050"],
    style: "后印象派",
    description: "塞尚以几何化的形体构建画面，开创了现代绘画的先河。",
  },
  {
    id: "where-do-we-come",
    subject: "叙事",
    studyTags: ["构图节奏", "冷暖关系"],
    studyPrompt:
      "只保留人群的剪影和背景两大色群；沿画面从左到右观察颜色与姿态的重复。",
    title: "Where Do We Come From? What Are We? Where Are We Going?",
    titleZh: "我们从哪里来？我们是什么？我们往哪里去？",
    artist: "Paul Gauguin",
    artistZh: "保罗·高更",
    year: "1897–1898",
    imageUrl: "/paintings/where-do-we-come.jpg",
    dominantColors: ["#2E5A2E", "#8B6914", "#C8A060", "#4A7A4A", "#D4B896"],
    style: "后印象派",
    description: "高更最重要的哲学性巨作，在塔希提岛创作，探讨生命的意义。",
  },
  {
    id: "vision-sermon",
    subject: "叙事",
    studyTags: ["冷暖关系", "构图节奏"],
    studyPrompt:
      "先画大块红色，再加入白色与暗色形；试着改变白色块的面积，观察画面的重心。",
    title: "Vision After the Sermon",
    titleZh: "布道后的幻象",
    artist: "Paul Gauguin",
    artistZh: "保罗·高更",
    year: "1888",
    imageUrl: "/paintings/vision-sermon.jpg",
    dominantColors: ["#C83228", "#2A3A2A", "#F5DEB3", "#8B1A1A", "#D4A090"],
    style: "后印象派",
    description: "大面积鲜红背景极具冲击力，标志着高更走向象征主义的转变。",
  },

  // ─── 表现主义 ─────────────────────────────────────────────
  {
    id: "the-scream",
    subject: "人物",
    studyTags: ["构图节奏", "冷暖关系"],
    studyPrompt:
      "分别用直线概括桥、曲线概括天空与人物；比较暖天空和冷水面的色彩对照。",
    title: "The Scream",
    titleZh: "呐喊",
    artist: "Edvard Munch",
    artistZh: "爱德华·蒙克",
    year: "1893",
    imageUrl: "/paintings/the-scream.jpg",
    dominantColors: ["#C0392B", "#E67E22", "#F39C12", "#2C3E50", "#8B4513"],
    style: "表现主义",
    description:
      "以扭曲线条和强烈色彩表达内心的恐惧与焦虑，是心理表现主义的标志。",
  },

  // ─── 新艺术运动 ───────────────────────────────────────────
  {
    id: "the-kiss-klimt",
    subject: "人物",
    studyTags: ["色彩调和", "构图节奏"],
    studyPrompt:
      "把金色大形和背景分开，观察长方形与圆形图案的重复；先画整体轮廓再加三处图案。",
    title: "The Kiss",
    titleZh: "吻",
    artist: "Gustav Klimt",
    artistZh: "古斯塔夫·克里姆特",
    year: "1907–1908",
    imageUrl: "/paintings/the-kiss-klimt.jpg",
    dominantColors: ["#DAA520", "#8B6914", "#F5DEB3", "#2C2416", "#C8A030"],
    style: "新艺术运动",
    description:
      "克里姆特黄金时期代表作，以大量金箔和华丽装饰图案表现爱情的永恒。",
  },

  // ─── 超现实主义 ───────────────────────────────────────────
  {
    id: "persistence-of-memory",
    subject: "叙事",
    studyTags: ["空间透视", "边缘虚实"],
    studyPrompt:
      "先比较远景与近物的大小和清晰程度，再挑一件物体用亮、中、暗塑造体积。",
    title: "The Persistence of Memory",
    titleZh: "记忆的永恒",
    artist: "Salvador Dalí",
    artistZh: "萨尔瓦多·达利",
    year: "1931",
    imageUrl: "/paintings/persistence-of-memory.jpg",
    dominantColors: ["#8B7355", "#D4B896", "#87CEEB", "#F5DEB3", "#4A3728"],
    style: "超现实主义",
    description: "超现实主义最具代表性的作品，以融化的钟表探讨时间的主观性。",
  },

  // ─── 古典主义 ─────────────────────────────────────────────
  {
    id: "liberty-leading",
    subject: "叙事",
    studyTags: ["构图节奏", "明暗归纳"],
    studyPrompt:
      "把人群概括成一个大三角，再切黑白找出主要亮块；最后只加红、白、蓝三个色点。",
    title: "Liberty Leading the People",
    titleZh: "自由引导人民",
    artist: "Eugène Delacroix",
    artistZh: "欧仁·德拉克罗瓦",
    year: "1830",
    imageUrl: "/paintings/liberty-leading.jpg",
    dominantColors: ["#1A237E", "#8B1A1A", "#F5DEB3", "#2C3A2C", "#C83228"],
    style: "浪漫主义",
    description:
      "以三色旗为象征，表现1830年法国七月革命中人民的英勇，充满热情与动感。",
  },
  {
    id: "raft-medusa",
    subject: "叙事",
    studyTags: ["构图节奏", "明暗归纳"],
    studyPrompt:
      "用几条斜线概括人群姿态与船筏方向，切黑白观察大暗形怎样托住亮部。",
    title: "The Raft of the Medusa",
    titleZh: "梅杜萨之筏",
    artist: "Théodore Géricault",
    artistZh: "泰奥多尔·席里柯",
    year: "1818–1819",
    imageUrl: "/paintings/raft-medusa.jpg",
    dominantColors: ["#8B6914", "#2C2416", "#C8A060", "#4A3A28", "#D4B896"],
    style: "浪漫主义",
    description:
      "根据真实海难事件创作，以金字塔式构图展现绝望与希望的戏剧张力。",
  },
  {
    id: "third-of-may",
    subject: "叙事",
    studyTags: ["明暗归纳", "构图节奏"],
    studyPrompt:
      "先把背景与人群画成一个暗块，再放入白衣亮块；观察最大明暗对比怎样突出中心。",
    title: "The Third of May 1808",
    titleZh: "1808年5月3日",
    artist: "Francisco Goya",
    artistZh: "弗朗西斯科·戈雅",
    year: "1814",
    imageUrl: "/paintings/third-of-may.jpg",
    dominantColors: ["#F5D060", "#2C2416", "#C83228", "#8B7355", "#FFFFFF"],
    style: "浪漫主义",
    description:
      "戈雅以白衫男子为焦点，强烈控诉战争暴行，是现代战争绘画的先驱。",
  },
  {
    id: "olympia",
    subject: "人物",
    studyTags: ["明暗归纳", "边缘虚实"],
    studyPrompt:
      "切黑白比较身体、床单与背景的明度；观察明亮形体的边缘哪里更清楚。",
    title: "Olympia",
    titleZh: "奥林匹亚",
    artist: "Édouard Manet",
    artistZh: "爱德华·马奈",
    year: "1863",
    imageUrl: "/paintings/olympia.jpg",
    dominantColors: ["#F5DEB3", "#2C2416", "#4A3728", "#8B7355", "#FFFFF0"],
    style: "现代主义先驱",
    description:
      "马奈以直白现代手法重诠古典题材，挑战学院派规范，引发巨大争议。",
  },

  // ─── 新印象派 / 点彩 ──────────────────────────────────────
  {
    id: "sunday-grande-jatte",
    subject: "人物",
    studyTags: ["构图节奏", "冷暖关系"],
    studyPrompt:
      "先将草地、人群与水面分成大色块，再放大看小色点；远看合并关系，近看颜色并置。",
    title: "A Sunday on La Grande Jatte",
    titleZh: "大碗岛的星期天下午",
    artist: "Georges Seurat",
    artistZh: "乔治·修拉",
    year: "1884–1886",
    imageUrl: "/paintings/sunday-grande-jatte.jpg",
    dominantColors: ["#3A6A3A", "#8BAA6A", "#C8C890", "#4A7A4A", "#A0C090"],
    style: "点彩派",
    description:
      "以细小纯色圆点构成画面，是点彩派（分色主义）技法的集大成之作。",
  },

  // ─── 现代主义 ─────────────────────────────────────────────
  {
    id: "nighthawks",
    subject: "室内",
    studyTags: ["空间透视", "冷暖关系"],
    studyPrompt:
      "比较室内灯光与室外街道的两大色群，沿柜台边线观察空间；先画亮暗面积比例。",
    title: "Nighthawks",
    titleZh: "夜鹰",
    artist: "Edward Hopper",
    artistZh: "爱德华·霍珀",
    year: "1942",
    imageUrl: "/paintings/nighthawks.jpg",
    dominantColors: ["#2A6A3A", "#C8A040", "#F5E890", "#1A2A1A", "#8BAA60"],
    style: "写实主义",
    description:
      "以孤寂的深夜餐厅描绘现代都市的疏离感，是美国20世纪最著名的绘画之一。",
  },
  {
    id: "american-gothic",
    subject: "人物",
    studyTags: ["构图节奏", "明暗归纳"],
    studyPrompt:
      "比较人物、窗和工具中重复的竖线；切黑白把两个人物与背景分成三个大形。",
    title: "American Gothic",
    titleZh: "美国哥特式",
    artist: "Grant Wood",
    artistZh: "格兰特·伍德",
    year: "1930",
    imageUrl: "/paintings/american-gothic.jpg",
    dominantColors: ["#8B6914", "#6B4A28", "#C8A060", "#4A3A28", "#D4B896"],
    style: "地域主义",
    description:
      "以农民夫妇和哥特式窗户为核心，成为美国中西部精神与价值观的象征。",
  },
  // 新增馆藏：AIC 公开 API 已标记为公共领域，图片与出处见公开清单。
  {
    id: "aic-20684",
    title: "Paris Street; Rainy Day",
    titleZh: "巴黎街道·雨天",
    artist: "Gustave Caillebotte",
    artistZh: "居斯塔夫·卡耶博特",
    year: "1877",
    imageUrl: "/paintings/aic-20684.jpg",
    dominantColors: ["#272E35", "#959693", "#686869", "#B1B1AB", "#D0C9BE"],
    style: "印象派",
    description:
      "先看街角的斜线，再比较近处与远处人物的大小，观察城市街道怎样产生纵深。",
    subject: "风景",
    studyTags: ["空间透视", "明暗归纳"],
    studyPrompt:
      "用尺子延长两侧建筑的边线，标出它们大致的汇聚方向；再画三个由大到小的人形，检验远近。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/20684",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-111436",
    title: "The Basket of Apples",
    titleZh: "苹果篮",
    artist: "Paul Cezanne",
    artistZh: "保罗·塞尚",
    year: "约 1893",
    imageUrl: "/paintings/aic-111436.jpg",
    dominantColors: ["#73674C", "#838774", "#51463A", "#919688", "#ACAB9A"],
    style: "后印象派",
    description:
      "圆润的水果、深色瓶子和浅色桌布，为观察形体与色块的组合提供了入口。",
    subject: "静物",
    studyTags: ["构图节奏", "冷暖关系"],
    studyPrompt:
      "先把苹果画成球、瓶子画成圆柱；只取暖黄、灰绿和深褐三组颜色，做一张巴掌大的色块稿。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/111436",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-25865",
    title: "The Herring Net",
    titleZh: "鲱鱼网",
    artist: "Winslow Homer",
    artistZh: "温斯洛·霍默",
    year: "1885",
    imageUrl: "/paintings/aic-25865.jpg",
    dominantColors: ["#76644D", "#352E20", "#7D6B53", "#5D5543", "#817B65"],
    style: "写实主义",
    description: "把人物、船和海浪归纳为几个大形，观察有限色彩中的亮暗变化。",
    subject: "人物",
    studyTags: ["明暗归纳", "边缘虚实"],
    studyPrompt:
      "切到黑白，用三个灰阶区分天空、海面与人物；让远处船只的边缘比近处人物更轻。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/25865",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-14655",
    title: "Two Sisters (On the Terrace)",
    titleZh: "姐妹俩（露台上）",
    artist: "Pierre-Auguste Renoir",
    artistZh: "皮埃尔·奥古斯特·雷诺阿",
    year: "1881",
    imageUrl: "/paintings/aic-14655.jpg",
    dominantColors: ["#76645C", "#838778", "#3A4954", "#9B9D90", "#B2B6B0"],
    style: "印象派",
    description: "深色衣服与明亮帽子形成醒目的对照，背景则由较小的色块组成。",
    subject: "人物",
    studyTags: ["冷暖关系", "构图节奏"],
    studyPrompt:
      "只临摹帽子、衣服和背景三块颜色；比较哪一块最鲜、哪一块最暗，再试着降低背景的饱和度。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/14655",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-61128",
    title: "At the Moulin Rouge",
    titleZh: "红磨坊",
    artist: "Henri de Toulouse-Lautrec",
    artistZh: "亨利·德·图卢兹-劳特累克",
    year: "1892–95",
    imageUrl: "/paintings/aic-61128.jpg",
    dominantColors: ["#593B14", "#282116", "#524729", "#472B13", "#666347"],
    style: "后印象派",
    description: "桌沿与人群把视线带进室内，人物面部呈现不寻常的冷暖对照。",
    subject: "室内",
    studyTags: ["冷暖关系", "构图节奏"],
    studyPrompt:
      "找出最暖和最冷的两块面部颜色，在纸上并排调出；再用三条线概括桌面与人物的位置。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/61128",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-94841",
    title: "The Song of the Lark",
    titleZh: "云雀之歌",
    artist: "Jules Breton",
    artistZh: "朱尔·布勒东",
    year: "1884",
    imageUrl: "/paintings/aic-94841.jpg",
    dominantColors: ["#504537", "#38342F", "#BA9A76", "#68614B", "#D4B17D"],
    style: "自然主义",
    description: "明亮天空衬托较暗的人物剪影，适合练习先统一大明暗，再补细节。",
    subject: "人物",
    studyTags: ["明暗归纳", "色彩调和"],
    studyPrompt:
      "先切黑白，把人物连同衣服涂成一个暗形；回到彩色后，在同一暗形中只找两处细微冷暖变化。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/94841",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-191183",
    title: "Madame Paul Escudier (Louise Lefevre)",
    titleZh: "保罗·埃斯屈迪耶夫人像",
    artist: "John Singer Sargent",
    artistZh: "约翰·辛格·萨金特",
    year: "1882",
    imageUrl: "/paintings/aic-191183.jpg",
    dominantColors: ["#181818", "#2C221C", "#291B17", "#3D2E24", "#8B7D6D"],
    style: "写实主义",
    description:
      "肖像中的脸部、衣物与背景，让初学者练习判断哪些轮廓清楚、哪些可以融入暗部。",
    subject: "人物",
    studyTags: ["明暗归纳", "边缘虚实"],
    studyPrompt:
      "眯眼找出脸部最亮的一块，比较它与衣物的明度；临摹时保留一处清楚轮廓，让另一处轮廓变柔。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/191183",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-111442",
    title: "The Child's Bath",
    titleZh: "给孩子洗澡",
    artist: "Mary Cassatt",
    artistZh: "玛丽·卡萨特",
    year: "1893",
    imageUrl: "/paintings/aic-111442.jpg",
    dominantColors: ["#5E5F5C", "#4C3D3E", "#7B7475", "#948E93", "#A5ACB3"],
    style: "印象派",
    description: "俯视角度下的水盆、身体与地面图案，适合练习椭圆和画面分组。",
    subject: "室内",
    studyTags: ["空间透视", "构图节奏"],
    studyPrompt:
      "轻轻画出水盆椭圆的长短轴，再把母亲和孩子概括为一个大形；避免先追逐衣服上的条纹。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/111442",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-69780",
    title: "The Fountain, Villa Torlonia, Frascati, Italy",
    titleZh: "托尔洛尼亚别墅的喷泉",
    artist: "John Singer Sargent",
    artistZh: "约翰·辛格·萨金特",
    year: "1907",
    imageUrl: "/paintings/aic-69780.jpg",
    dominantColors: ["#3F4536", "#63513B", "#7F785E", "#9C9B89", "#C2C7B8"],
    style: "写实主义",
    description: "明暗交错的花园环境，适合比较阳光下与阴影里的浅色物体。",
    subject: "风景",
    studyTags: ["冷暖关系", "边缘虚实"],
    studyPrompt:
      "选择一处受光浅色和一处阴影浅色，并排画两个小色块；先比较明度，再判断冷暖。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/69780",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-14620",
    title: "Cliff Walk at Pourville",
    titleZh: "普尔维尔悬崖漫步",
    artist: "Claude Monet",
    artistZh: "克劳德·莫奈",
    year: "1882",
    imageUrl: "/paintings/aic-14620.jpg",
    dominantColors: ["#8D9FAE", "#828D89", "#75776C", "#89969A", "#A5A6A9"],
    style: "印象派",
    description:
      "前景草地与远处海面分成不同色群，可用来练习空间层次与相邻色对比。",
    subject: "风景",
    studyTags: ["空间透视", "冷暖关系"],
    studyPrompt:
      "只用前景、中景、远景三条宽色带概括画面；比较远处色彩是否更接近天空，再加一笔人物。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/14620",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-20701",
    title: "Waterloo Bridge, Sunlight Effect",
    titleZh: "滑铁卢桥·阳光效果",
    artist: "Claude Monet",
    artistZh: "克劳德·莫奈",
    year: "1903",
    imageUrl: "/paintings/aic-20701.jpg",
    dominantColors: ["#8C90AF", "#8B86A3", "#757EA6", "#9593AE", "#9F96AA"],
    style: "印象派",
    description: "雾气中的桥和河流，适合练习相近色之间的细微区分。",
    subject: "风景",
    studyTags: ["色彩调和", "边缘虚实"],
    studyPrompt:
      "找三块看起来接近的灰色，分别判断偏黄、偏紫还是偏蓝；只用这三色画出桥与水面。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/20701",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-81537",
    title: "Bordighera",
    titleZh: "博尔迪盖拉",
    artist: "Claude Monet",
    artistZh: "克劳德·莫奈",
    year: "1884",
    imageUrl: "/paintings/aic-81537.jpg",
    dominantColors: ["#4D574B", "#626A4F", "#343832", "#707857", "#829180"],
    style: "印象派",
    description:
      "树木、建筑和远景形成层层叠加的色块，可从大面积的绿与暖色开始观察。",
    subject: "风景",
    studyTags: ["冷暖关系", "构图节奏"],
    studyPrompt:
      "把繁密树叶合并为三块绿色，比较它们的冷暖与明度；先画大色块，最后才添加少量枝条。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/81537",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-16487",
    title: "The Bay of Marseille, Seen from L'Estaque",
    titleZh: "从埃斯塔克看马赛湾",
    artist: "Paul Cezanne",
    artistZh: "保罗·塞尚",
    year: "约 1885",
    imageUrl: "/paintings/aic-16487.jpg",
    dominantColors: ["#476979", "#70716A", "#7B9395", "#9CA9A4", "#A38F74"],
    style: "后印象派",
    description:
      "建筑、山与海可以归纳成稳定的几何色块，适合从素描形体过渡到油画。",
    subject: "风景",
    studyTags: ["空间透视", "色彩调和"],
    studyPrompt:
      "用长方体概括近处房屋，用大三角概括远山；每层只选一种主色，检查远近层次是否清楚。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/16487",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-16549",
    title: "Apples and Grapes",
    titleZh: "苹果与葡萄",
    artist: "Claude Monet",
    artistZh: "克劳德·莫奈",
    year: "1880",
    imageUrl: "/paintings/aic-16549.jpg",
    dominantColors: ["#A3A39E", "#83807D", "#524B48", "#7B6D68", "#646768"],
    style: "印象派",
    description: "静物里不同水果与布面相互衬托，可从一组亮色与暗色开始练习。",
    subject: "静物",
    studyTags: ["冷暖关系", "边缘虚实"],
    studyPrompt:
      "选一个苹果，只用亮面、灰面、暗面三块塑造；留一处边缘与背景相融，避免每个苹果都勾一圈。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/16549",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-84709",
    title: "Still Life with Game Fowl",
    titleZh: "野禽静物",
    artist: "Juan Sánchez Cotán",
    artistZh: "胡安·桑切斯·科坦",
    year: "约 1600–3",
    imageUrl: "/paintings/aic-84709.jpg",
    dominantColors: ["#403523", "#13100E", "#282015", "#776748", "#1B1711"],
    style: "巴洛克",
    description: "明亮物体与深暗背景形成直接对比，适合练习剪影和亮部的组织。",
    subject: "静物",
    studyTags: ["明暗归纳", "构图节奏"],
    studyPrompt:
      "先把背景涂成一个统一暗块，再画三个最亮的形；最后比较哪些悬挂物之间的空隙最重要。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/84709",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-62450",
    title: "Still Life with a Basket of Fruit and a Bunch of Asparagus",
    titleZh: "果篮与一束芦笋",
    artist: "Louise Moillon",
    artistZh: "路易丝·穆瓦永",
    year: "1630",
    imageUrl: "/paintings/aic-62450.jpg",
    dominantColors: ["#402118", "#1D0512", "#866643", "#1A040F", "#290912"],
    style: "巴洛克",
    description: "水果、篮子与芦笋提供了不同形体与质感的观察对象。",
    subject: "静物",
    studyTags: ["明暗归纳", "冷暖关系"],
    studyPrompt:
      "用一盏灯照自己的水果，比较画中水果的亮面与暗面；只画一个球形水果和它落在桌面的投影。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/62450",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on panel",
  },
  {
    id: "aic-94126",
    title: "Still Life with Monkey, Fruits, and Flowers",
    titleZh: "猴子、水果与鲜花静物",
    artist: "Jean-Baptiste Oudry",
    artistZh: "让-巴蒂斯特·乌德里",
    year: "1724",
    imageUrl: "/paintings/aic-94126.jpg",
    dominantColors: ["#56402B", "#34251D", "#92967C", "#756D51", "#A0A992"],
    style: "巴洛克",
    description: "多种物体挤在同一画面里，可练习先合并大形，再找视觉重点。",
    subject: "静物",
    studyTags: ["构图节奏", "色彩调和"],
    studyPrompt:
      "暂时忽略物件名称，把画面概括成三个大色团；圈出你第一眼看到的亮点，其他地方少加细节。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/94126",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-65811",
    title: "The Plate of Apples",
    titleZh: "一盘苹果",
    artist: "Paul Cezanne",
    artistZh: "保罗·塞尚",
    year: "约 1877",
    imageUrl: "/paintings/aic-65811.jpg",
    dominantColors: ["#8E6F43", "#686655", "#8B7A52", "#878265", "#92967E"],
    style: "后印象派",
    description: "盘沿椭圆与苹果的体积，是把几何体练习带到静物中的直接例子。",
    subject: "静物",
    studyTags: ["空间透视", "冷暖关系"],
    studyPrompt:
      "画出盘子的椭圆长短轴，再把苹果摆入其中；从色板挑一个暖色与一个冷色，尝试表现球面的转折。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/65811",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-110663",
    title: "The Combat of the Giaour and Hassan",
    titleZh: "异教徒与哈桑的战斗",
    artist: "Eugène Delacroix",
    artistZh: "欧仁·德拉克罗瓦",
    year: "1826",
    imageUrl: "/paintings/aic-110663.jpg",
    dominantColors: ["#2A2621", "#47372A", "#5C5446", "#6B6555", "#897C64"],
    style: "浪漫主义",
    description: "交错的动作与明暗构成强烈动势，可以只研究画面的方向和大形。",
    subject: "叙事",
    studyTags: ["构图节奏", "明暗归纳"],
    studyPrompt:
      "用三条斜线概括主要动作，再切黑白合并人物与马匹的暗部；先看整体是否连贯，再画细节。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/110663",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-59002",
    title: "Souvenir of the Environs of Lake Nemi",
    titleZh: "内米湖附近的回忆",
    artist: "Jean Baptiste Camille Corot",
    artistZh: "让-巴蒂斯特·卡米耶·柯罗",
    year: "1865",
    imageUrl: "/paintings/aic-59002.jpg",
    dominantColors: ["#95A89A", "#231B04", "#332B11", "#48472D", "#282610"],
    style: "巴比松画派",
    description: "树木、天空和远景以柔和色群相连，适合练习低饱和色彩的层次。",
    subject: "风景",
    studyTags: ["色彩调和", "空间透视"],
    studyPrompt:
      "从色板选三个灰绿，依明度排成一列；分别用于近树、中景和远处，比较空间是否拉开。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/59002",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-94840",
    title: "Young Woman at an Open Half-Door",
    titleZh: "半开门后的年轻女子",
    artist: "Workshop of Rembrandt van Rijn",
    artistZh: "伦勃朗·范·莱因工作室",
    year: "1645",
    imageUrl: "/paintings/aic-94840.jpg",
    dominantColors: ["#32251C", "#281E18", "#503C2C", "#2D2018", "#211A16"],
    style: "巴洛克",
    description: "门框与人物构成简单的大明暗关系，可练习在暗背景中塑造脸与手。",
    subject: "人物",
    studyTags: ["明暗归纳", "边缘虚实"],
    studyPrompt:
      "只用三个灰阶概括脸、衣服和背景；找一处暗侧轮廓，把它与背景连起来，保留亮侧的转折。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/94840",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-64001",
    title: "Apples",
    titleZh: "苹果",
    artist: "Henri Matisse",
    artistZh: "亨利·马蒂斯",
    year: "1916",
    imageUrl: "/paintings/aic-64001.jpg",
    dominantColors: ["#221D1B", "#B97742", "#D6A359", "#773C26", "#C19D58"],
    style: "现代主义",
    description: "简化的静物色块适合练习相邻颜色的关系，而不急着描写表面细节。",
    subject: "静物",
    studyTags: ["色彩调和", "构图节奏"],
    studyPrompt:
      "先选画面里面积最大的三种色；将它们按原画大致比例排在纸上，再移动小色块观察视觉重心。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/64001",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-110541",
    title: "The Crystal Palace",
    titleZh: "水晶宫",
    artist: "Camille Pissarro",
    artistZh: "卡米耶·毕沙罗",
    year: "1871",
    imageUrl: "/paintings/aic-110541.jpg",
    dominantColors: ["#7E746B", "#4A423B", "#B5B7B4", "#9EA19D", "#C9C8C2"],
    style: "印象派",
    description: "道路、建筑与人物相互比较，帮助理解远近大小和地面纵深。",
    subject: "风景",
    studyTags: ["空间透视", "明暗归纳"],
    studyPrompt:
      "标出道路往远处收拢的方向，再画出近、中、远三个人物的高度；最后只用三档灰度填大形。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/110541",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-81551",
    title: "The Place du Havre, Paris",
    titleZh: "巴黎勒阿弗尔广场",
    artist: "Camille Pissarro",
    artistZh: "卡米耶·毕沙罗",
    year: "1893",
    imageUrl: "/paintings/aic-81551.jpg",
    dominantColors: ["#878788", "#9F9D96", "#64656A", "#B2AC9D", "#BDBFB5"],
    style: "印象派",
    description:
      "俯视街道中的建筑、车辆与行人，适合练习把复杂场景简化成大小不同的形。",
    subject: "风景",
    studyTags: ["空间透视", "构图节奏"],
    studyPrompt:
      "先找最大的建筑块和街道空地，再用点和短线表示行人与车辆；比较近处和远处细节的密度。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/81551",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-154235",
    title: "The Girl by the Window",
    titleZh: "窗边的女孩",
    artist: "Edvard Munch",
    artistZh: "爱德华·蒙克",
    year: "1893",
    imageUrl: "/paintings/aic-154235.jpg",
    dominantColors: ["#4A454B", "#3A3239", "#7A859A", "#646774", "#8B9BB0"],
    style: "表现主义",
    description: "窗口的亮部与室内暗部相互对照，适合用有限色彩组织安静的空间。",
    subject: "室内",
    studyTags: ["明暗归纳", "色彩调和"],
    studyPrompt:
      "切黑白后，把室内合并为一个暗形，只留下窗与人物的区别；回到彩色，再加入两种偏冷的灰色。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/154235",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-144969",
    title: "The Interior of the Palm House on the Pfaueninsel Near Potsdam",
    titleZh: "波茨坦孔雀岛棕榈温室内部",
    artist: "Carl Blechen",
    artistZh: "卡尔·布莱亨",
    year: "1834",
    imageUrl: "/paintings/aic-144969.jpg",
    dominantColors: ["#23260F", "#413C1A", "#61603A", "#807F5A", "#B5A278"],
    style: "浪漫主义",
    description:
      "室内结构与茂密植物叠加，既可以研究透视，也可以练习从繁杂细节里找大块光影。",
    subject: "室内",
    studyTags: ["空间透视", "明暗归纳"],
    studyPrompt:
      "用尺子找两组建筑线的汇聚方向，再把植物先归为暗形；窗边亮部留白，最后点出少数叶片。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/144969",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-9",
    title: "Interior of St. Mark's, Venice",
    titleZh: "威尼斯圣马可教堂内部",
    artist: "David Dalhoff Neal",
    artistZh: "大卫·达尔霍夫·尼尔",
    year: "1869",
    imageUrl: "/paintings/aic-9.jpg",
    dominantColors: ["#795C33", "#A18354", "#201910", "#392C1F", "#53391D"],
    style: "写实主义",
    description: "教堂内部的柱、拱与地面提供了观察室内纵深和亮暗分组的例子。",
    subject: "室内",
    studyTags: ["空间透视", "明暗归纳"],
    studyPrompt:
      "沿着地面与建筑边缘寻找纵深线，再把柱子概括成圆柱；先用三档灰度表现前后，不急于画装饰。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/9",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-6009",
    title: "The Beggar Boy (The Young Pilgrim)",
    titleZh: "乞讨男孩（年轻的朝圣者）",
    artist: "Giovanni Battista Piazzetta",
    artistZh: "乔瓦尼·巴蒂斯塔·皮亚泽塔",
    year: "1738–39",
    imageUrl: "/paintings/aic-6009.jpg",
    dominantColors: ["#1F190E", "#342815", "#18100A", "#CAC2AB", "#836441"],
    style: "洛可可",
    description: "人物的亮部在深色环境中显现，可用来练习脸部体积和柔硬边缘。",
    subject: "人物",
    studyTags: ["明暗归纳", "边缘虚实"],
    studyPrompt:
      "把脸分成亮、中、暗三面，检查最暗处是否仍比背景更亮；只在焦点附近保留清楚的小细节。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/6009",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-14647",
    title: "Young Woman Sewing",
    titleZh: "缝纫的年轻女子",
    artist: "Pierre-Auguste Renoir",
    artistZh: "皮埃尔·奥古斯特·雷诺阿",
    year: "1879",
    imageUrl: "/paintings/aic-14647.jpg",
    dominantColors: ["#647689", "#2A4163", "#625669", "#7A8992", "#9EAAA4"],
    style: "印象派",
    description: "衣服、肤色与背景的柔和关系，适合练习浅色物体里的冷暖变化。",
    subject: "人物",
    studyTags: ["冷暖关系", "边缘虚实"],
    studyPrompt:
      "在浅色衣服中找一块偏暖、一块偏冷的颜色；保持两块明度接近，用柔和边缘连接它们。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/14647",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
  {
    id: "aic-28862",
    title: "A Peasant Woman Digging in Front of Her Cottage",
    titleZh: "农舍前挖地的农妇",
    artist: "Vincent van Gogh",
    artistZh: "文森特·梵高",
    year: "约 1885",
    imageUrl: "/paintings/aic-28862.jpg",
    dominantColors: ["#7C7056", "#514B3D", "#C0C2BA", "#CED1C5", "#9F9680"],
    style: "后印象派",
    description:
      "偏深的土地与人物，适合练习有限的土色系以及不靠鲜艳颜色建立层次。",
    subject: "人物",
    studyTags: ["明暗归纳", "色彩调和"],
    studyPrompt:
      "只用土黄、褐色与白色画一个小色稿；先拉开天空、农舍和人物的明度，再比较两种褐色的冷暖。",
    museum: "芝加哥艺术博物馆",
    sourceUrl: "https://www.artic.edu/artworks/28862",
    license: "公共领域 · CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    medium: "Oil on canvas",
  },
];

export const PAINTERS = [...new Set(FAMOUS_PAINTINGS.map((p) => p.artistZh))];
export const STYLES = [...new Set(FAMOUS_PAINTINGS.map((p) => p.style))];

export const PAINTING_SUBJECTS = [
  ...new Set(FAMOUS_PAINTINGS.flatMap((p) => (p.subject ? [p.subject] : []))),
];
export const STUDY_TOPICS = [
  "明暗归纳",
  "冷暖关系",
  "空间透视",
  "边缘虚实",
  "构图节奏",
  "色彩调和",
];
